CREATE TABLE Users
(
    Id NVARCHAR(255) PRIMARY KEY,
    FirstName NVARCHAR(255) NOT NULL,
    LastName NVARCHAR(255) NOT NULL
);

CREATE TABLE Contacts
(
    Id NVARCHAR(255) PRIMARY KEY,
    Type NVARCHAR(255) NOT NULL,
    Detail NVARCHAR(255) NOT NULL,
    UserId NVARCHAR(255) NOT NULL,
    FOREIGN KEY(UserId) REFERENCES Users(Id)
);

CREATE TABLE Addresses
(
    Id NVARCHAR(255) PRIMARY KEY,
    City NVARCHAR(255) NOT NULL,
    State NVARCHAR(255) NOT NULL,
    Postcode NVARCHAR(255) NOT NULL,
    UserId NVARCHAR(255) NOT NULL,
    FOREIGN KEY(UserId) REFERENCES Users(Id)
);
